import { ChatMessage, Finding, SongSection, AssetMetadata } from '../types';
import { DSPAnalyzer } from './DSPAnalyzer';

export interface ChatContext {
  trackName: string | null;
  duration: number;
  currentTime: number;
  currentSection: SongSection | null;
  sections: SongSection[];
  selectedFinding: Finding | null;
  windowedPowers: number[];
  allFindings: Finding[];
  assetMetadata: AssetMetadata | null;
}

export class AssistantService {
  static buildContextString(context: ChatContext): string {
    const { trackName, duration, currentTime, currentSection, sections, selectedFinding, windowedPowers, allFindings, assetMetadata } = context;

    let ctxStr = `Track Metadata:
- Name: ${trackName || 'Untitled Track'}
- Total Duration: ${duration.toFixed(1)} seconds
- Current Playhead: ${currentTime.toFixed(1)} seconds

`;

    if (assetMetadata) {
      ctxStr += `User-Provided Asset Context:\n`;
      ctxStr += `- Asset Type: ${assetMetadata.assetType}\n`;
      ctxStr += `- Content: ${assetMetadata.content || 'N/A'}\n`;
      if (assetMetadata.userLabel) {
        ctxStr += `- User Label: ${assetMetadata.userLabel}\n`;
      }
      ctxStr += `\n`;
    }

    ctxStr += `Artist-Defined Facts:\n`;
    if (sections.length > 0) {
      ctxStr += `Sections (Authoritative Structure):\n`;
      sections.forEach(s => {
        ctxStr += `- [${s.timeRange.start.toFixed(1)}s - ${s.timeRange.end ? s.timeRange.end.toFixed(1) : duration.toFixed(1)}s]: ${s.name}\n`;
      });
      ctxStr += `\n`;
    } else {
      ctxStr += `Sections: None defined yet.\n\n`;
    }

    if (currentSection) {
      ctxStr += `The playhead is currently inside section: "${currentSection.name}".\n\n`;
    } else {
      ctxStr += `The playhead is not currently in any defined section.\n\n`;
    }

    ctxStr += `Measured Audio Facts — Real DSP:\n`;
    if (windowedPowers && windowedPowers.length > 0 && sections.length > 0) {
      const sectionEnergies = DSPAnalyzer.calculateSectionEnergies(windowedPowers, 0.5, sections);
      ctxStr += `Section Measurements (Average Energy & Audio Activity):\n`;
      sectionEnergies.forEach(se => {
        const silencePct = Math.max(0, 100 - se.activityPercentage);
        ctxStr += `- ${se.section.name}: ${se.averageDBFS.toFixed(1)} dBFS | ${se.activityPercentage.toFixed(0)}% Active Audio, ${silencePct.toFixed(0)}% Silence/Near-Silence\n`;
      });
      ctxStr += `\nSection-to-Section Energy Changes:\n`;
      for (let i = 0; i < sectionEnergies.length - 1; i++) {
        const current = sectionEnergies[i];
        const next = sectionEnergies[i + 1];
        const diffDB = next.averageDBFS - current.averageDBFS;
        ctxStr += `- ${current.section.name} -> ${next.section.name}: ${(diffDB > 0 ? '+' : '')}${diffDB.toFixed(1)} dB\n`;
      }
      ctxStr += `\n`;
    } else {
      ctxStr += `Section Measurements: Unavailable (DSP not run or sections not defined).\n`;
      ctxStr += `Section-to-Section Energy Changes: Unavailable.\n\n`;
    }

    const realFindings = (allFindings || []).filter(f => f.provenance === 'real-dsp');
    if (realFindings.length > 0) {
      ctxStr += `Relevant Real-DSP Findings:\n`;
      realFindings.forEach(f => {
         ctxStr += `- [${f.category.toUpperCase()}] ${f.observation} (Confidence: ${f.confidence}%)\n`;
         ctxStr += `  Evidence: ${f.evidence}\n`;
      });
      ctxStr += `\n`;
    }

    ctxStr += `Unavailable Measurements:\n`;
    ctxStr += `DO NOT imply spectral balance, masking, transient response, stereo width, LUFS, or frequency-specific information exist. These have NOT been measured.\n\n`;

    if (selectedFinding) {
      const isMock = selectedFinding.provenance === 'mock';
      ctxStr += `Currently Selected Finding:\n`;
      if (isMock) {
        ctxStr += `*** IMPORTANT: THIS IS MOCK DATA/DEVELOPMENT DATA. DO NOT TREAT IT AS A REAL MEASUREMENT ***\n`;
      } else {
        ctxStr += `*** REAL MEASUREMENT DATA GENERATED BY DSP ANALYZER ***\n`;
      }
      ctxStr += `- Observation: ${selectedFinding.observation}
- Category: ${selectedFinding.category}
- Provenance: ${selectedFinding.provenance}
- Time Range: ${selectedFinding.timeRange.start.toFixed(1)}s - ${selectedFinding.timeRange.end ? selectedFinding.timeRange.end.toFixed(1) : duration.toFixed(1)}s
- Evidence: ${selectedFinding.evidence}
- Explanation: ${selectedFinding.explanation}
- Recommendation: ${selectedFinding.recommendation}
- Triage Status: ${selectedFinding.userStatus}
\n`;
    } else {
      ctxStr += `Currently Selected Finding: None.\n\n`;
    }

    return ctxStr;
  }

  static async sendMessage(messages: ChatMessage[], context: ChatContext, signal?: AbortSignal): Promise<string> {
    const contextString = this.buildContextString(context);

    const response = await fetch('/api/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        messages,
        context: contextString
      }),
      signal
    });

    if (!response.ok) {
      const err = await response.json().catch(() => ({}));
      throw new Error(err.error || 'Failed to communicate with Assistant');
    }

    const data = await response.json();
    return data.text;
  }
}
